### ISSUE TITLE
Does not work with v2 Lighthouses

### ISSUE THREAD

**Issue by sparker256** [mann1x/BSManager#2]
I am trying to use this with my v2 light houses but it is not finding them. It is detecting when my 8KX is on and off.

I have been using lighthouse-v2-manager.exe from https://github.com/nouser2013/lighthouse-v2-manager/releases and it works fine so sure my blue tooth adapter is working.

**Comment by mann1x** [comment]
Thanks for testing!

Does it find the Base Stations?
DO you see them listed in the menu?

**Comment by sparker256** [comment]
No it says Discovered: 0

**Comment by mann1x** [comment]
Do you have the base stations paired in Windows settings?

**Comment by sparker256** [comment]
No I have never did that before so might need some instruction or is it documented somewhere?

**Comment by mann1x** [comment]
First, do you have a Bluetooth adapter (which is not in a VR Headset like the Vive)?

**Comment by sparker256** [comment]
Yes it a USB dongle.

**Comment by mann1x** [comment]
I have a food delivery :) will come back in a while

Search with Windows the basestations, their name should start with LHB- XXXX and pair them

**Comment by sparker256** [comment]
OK will have a look

**Comment by mann1x** [comment]
Yes, I see in the code that I'm looking for devices starting with: "LHB-".
You should be able to see them also via scan Bluetooth on a mobile phone.

If you see them with the phone then their are not paired in Windows.

In Windows 10, Settings, Devices, Add Bluetooth or other device
The choose Bluetooth and look for the 2 Base Stations

Click on them and Windows should start the pairing

**Comment by sparker256** [comment]
Yes I found it but do not know the pin number so will need that to get further.

Thanks for your help.

**Comment by mann1x** [comment]
Weird is asking, anyway should be "0000"

**Comment by mann1x** [comment]
You are also using the Python script... it should ask as well to have the base stations already paired in Windows.
Maybe it's because it's connecting to them directly with the MAC address.
Quite puzzling... can you confirm the Bluetooth names are starting with "LHB-"?

**Comment by sparker256** [comment]
Yes how I am currently turning them on and off is by using the MAC address.

LHB-D0339852
LHB-4ED!BBC0
LHB-0D6777AF

**Comment by mann1x** [comment]
Ouch sorry :)
Most stupid error copying the regexp for the v1
Give me 10 minutes and I'll release a fixed version

**Comment by sparker256** [comment]
Sounds good will be here to test.

**Comment by mann1x** [comment]
Now if you quit and re-open should ask you to upgrade (hopefully) to 1.2.4

**Comment by mann1x** [comment]
For some reason the AutoUpdater decided to stop working so you have to update manually...

**Comment by sparker256** [comment]
It did seem to update from 1.2.3 to 1.2.4 but it still does not find my Light housed even though they are Paired.

**Comment by mann1x** [comment]
this is really odd...

Can you please download:

https://github.com/sensboston/BLEConsole/tree/master/BLEConsole

And post here the output of the command List?

**Comment by mann1x** [comment]
By any chance do you use Discord?

**Comment by sparker256** [comment]
Sorry one of my light houses went missing and had to find it.
I am on discord SparkerInVR#6781

**Comment by mann1x** [comment]
Let me know if 1.2.5 fixed it, found what was probably the issue (wrong BLE characteristic)
I've also improved the reliability of the SteamVR DB parsing, you should not get anymore the biblical list but only 3 serials

**Comment by sparker256** [comment]
The SteamVR DB parsing is working correctly but still not turning on the light houses. I am getting the PIMAX ON but nothing else.

Force Sleep does not work.

**Comment by mann1x** [comment]
we need to try again with BLEConsole...
The usual List and Open

The try 

SET 00001525-1212-efde-1523-785feabcd124

**Comment by mann1x** [comment]
Another test:

SET 5413

WRITE 5413 01

**Comment by mann1x** [comment]
If the above SET doesn't work try

SET 5411

and then Write

**Comment by sparker256** [comment]
I did your tests this morning and still not working.

**Comment by mann1x** [comment]
Please test this version:

https://github.com/mann1x/BSManager/releases/tag/1.2.6_debug

It will create a BSManager.log file in the directory where it runs.
Post here the file or send it via Discord.

Thanks!

**Comment by mann1x** [comment]
New updated debug version

https://github.com/mann1x/BSManager/releases/tag/1.2.7_debug

This one has a switch in the Help menu to enable the debug log

**Comment by mann1x** [comment]
An exception is occurring but I wasn't recording the message in the log
Try now with this:

https://github.com/mann1x/BSManager/releases/tag/v1.2.8_debug
